### ISSUE TITLE
crashlytics_build.xml not found, if plugin is disabled in uproject setting

### ISSUE THREAD

**Issue by bellinykim** [gameDNAstudio/Crashlytics#2]
when Crashlytics plugin is disabled and doing Android Cooking,
<img width="318" alt="screen shot 2017-03-18 at 5 37 38 pm" src="https://cloud.githubusercontent.com/assets/11987298/24070481/a40e593a-0c01-11e7-9314-dc794da79769.png">

facing this error message.

UATHelper: Packaging (Android (ASTC)): UnrealBuildTool: BUILD FAILED
UATHelper: Packaging (Android (ASTC)): UnrealBuildTool: D:\{projectname}\Intermediate\Android\APK\build.xml:69: The following error occurred while executing this line:
UATHelper: Packaging (Android (ASTC)): UnrealBuildTool: D:\{projectname}\Intermediate\Android\APK\custom_rules.xml:3: Cannot find D:\{projectname}\Intermediate\Android\APK\crashlytics_build.xml imported from D:\{projectname}\Intermediate\Android\APK\custom_rules.xml
UATHelper: Packaging (Android (ASTC)): UnrealBuildTool: 
UATHelper: Packaging (Android (ASTC)): UnrealBuildTool: Total time: 0 seconds

-------------
what i've thought is,
custom_ruiles.xml defines [import "crashlytics_build.xml"] and it can't be referenced once plugin is disabled.

would you check it please?

**Comment by gameDNA-Helix** [comment]
It's not possible to control custom_rules.xml via plugin. You should remove this line manually and delete [PROJECT_FOLDER]/Intermediate. After this steps, build should be successful.
