### ISSUE TITLE
Crashlytics won't initialized if built for arm64 only

### ISSUE THREAD

**Issue by bellinykim** [gameDNAstudio/Crashlytics#3]
if ue4 project is built only for arm64[arm64-v8a], the app won't start with failure of crashlytics initialization(missing libcrashlytics.so).

what i guess is, libcrashytics.so is referenced by $Architecture for copying but final destination is always armeabi-v7a(armv7) not suitable for arm64 architecture.

... Crashlytics_UPL_Android.xml ...
```
  <resourceCopies>
	  <copyFile src="$S(PluginDir)/../../Source/ThirdParty/AndroidLibs/$S(Architecture)/libcrashlytics.so"
				  dst="$S(BuildDir)/libs/armeabi-v7a/libcrashlytics.so" />
	  <copyFile src="$S(PluginDir)/../../Source/ThirdParty/AndroidLibs/$S(Architecture)/libcrashlytics-envelope.so"
					dst="$S(BuildDir)/libs/armeabi-v7a/libcrashlytics-envelope.so" />
	  <copyFile src="$S(PluginDir)/../../Source/ThirdParty/AndroidLibs/$S(Architecture)/libunwind-crashlytics.so"
				  dst="$S(BuildDir)/libs/armeabi-v7a/libunwind-crashlytics.so" />
  </resourceCopies>
```

[btw, thank you for all your supporting 👍. i missed saying it so far. X-D)

**Comment by gameDNA-Helix** [comment]
Fixed in this commit: https://github.com/gameDNAstudio/Crashlytics/commit/173e57894fe25c672851fabb62e67494ca2191c3
