### ISSUE TITLE
Plugin Build Script Error in UE4.18.3

### ISSUE THREAD

**Issue by choigawoon** [gameDNAstudio/Crashlytics#4]
{ProjectName}\Plugins\Crashlytics\Source\Crashlytics\Crashlytics.Build.cs

// Crashlytics Plugin
// Created by Patryk Stepniewski
// Copyright (c) 2014-2018 gameDNA Ltd. All Rights Reserved.

using System.IO;

namespace UnrealBuildTool.Rules
{
	public class Crashlytics : ModuleRules
	{
		public Crashlytics(ReadOnlyTargetRules Target) : base(Target)
		{
			PCHUsage = PCHUsageMode.UseExplicitOrSharedPCHs;

			Definitions.Add("WITH_CRASHLYTICS=1"); // fixed

			PublicIncludePaths.Add("Crashlytics/Public");
			PrivateIncludePaths.Add("Crashlytics/Private");

            PublicDependencyModuleNames.AddRange(new string[] { "Engine", "Core", "CoreUObject" });
			PrivateIncludePathModuleNames.AddRange(new string[] { "Settings" });

			// Additional Frameworks and Libraries for iOS
			if (Target.Platform == UnrealTargetPlatform.IOS)
			{
				PublicAdditionalFrameworks.Add(
						new UEBuildFramework(
							"Fabric",
							"../ThirdParty/iOS/Fabric.embeddedframework.zip"
						)
				);

				PublicAdditionalFrameworks.Add(
						new UEBuildFramework(
							"Crashlytics",
							"../ThirdParty/iOS/Crashlytics.embeddedframework.zip"
						)
				);

				string PluginPath = Utils.MakePathRelativeTo(ModuleDirectory, Target.RelativeEnginePath);
				AdditionalPropertiesForReceipt.Add(new ReceiptProperty("IOSPlugin", Path.Combine(PluginPath, "Crashlytics_UPL_IOS.xml")));// fixed
			}
			// Additional Frameworks and Libraries for Android
			else if (Target.Platform == UnrealTargetPlatform.Android)
			{
				PrivateDependencyModuleNames.AddRange(new string[] { "Launch" });
				string PluginPath = Utils.MakePathRelativeTo(ModuleDirectory, Target.RelativeEnginePath);
				AdditionalPropertiesForReceipt.Add(new ReceiptProperty("AndroidPlugin", Path.Combine(PluginPath, "Crashlytics_UPL_Android.xml"))); // fixed
			}
		}
	}
}

**Comment by gameDNA-Helix** [comment]
Hello,

what exactly did you change? Because I don't see any difference...
